name: mirror to tangled

on:
  push: {}
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: gwennlbh/to-tangled@v0.5
        with:
          repo: likes.fyi/website
          ssh-key: ${{ secrets.TANGLED_MIRROR_KEY }}
